//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4.RegistrosService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegistrosService.RegistrosSoap")]
    public interface RegistrosSoap {
        
        // CODEGEN: Generating message contract since element name identificacao from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AtualizarRegistros", ReplyAction="*")]
        M4.RegistrosService.AtualizarRegistrosResponse AtualizarRegistros(M4.RegistrosService.AtualizarRegistrosRequest request);
        
        // CODEGEN: Generating message contract since element name identificacao from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrosPorAtivo", ReplyAction="*")]
        M4.RegistrosService.RegistrosPorAtivoResponse RegistrosPorAtivo(M4.RegistrosService.RegistrosPorAtivoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AtualizarRegistrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AtualizarRegistros", Namespace="http://tempuri.org/", Order=0)]
        public M4.RegistrosService.AtualizarRegistrosRequestBody Body;
        
        public AtualizarRegistrosRequest() {
        }
        
        public AtualizarRegistrosRequest(M4.RegistrosService.AtualizarRegistrosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AtualizarRegistrosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identificacao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string crc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string codigo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string primeiroRegistro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ultimoRegistro;
        
        public AtualizarRegistrosRequestBody() {
        }
        
        public AtualizarRegistrosRequestBody(string identificacao, string crc, string codigo, string primeiroRegistro, string ultimoRegistro) {
            this.identificacao = identificacao;
            this.crc = crc;
            this.codigo = codigo;
            this.primeiroRegistro = primeiroRegistro;
            this.ultimoRegistro = ultimoRegistro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AtualizarRegistrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AtualizarRegistrosResponse", Namespace="http://tempuri.org/", Order=0)]
        public M4.RegistrosService.AtualizarRegistrosResponseBody Body;
        
        public AtualizarRegistrosResponse() {
        }
        
        public AtualizarRegistrosResponse(M4.RegistrosService.AtualizarRegistrosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AtualizarRegistrosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement AtualizarRegistrosResult;
        
        public AtualizarRegistrosResponseBody() {
        }
        
        public AtualizarRegistrosResponseBody(System.Xml.Linq.XElement AtualizarRegistrosResult) {
            this.AtualizarRegistrosResult = AtualizarRegistrosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrosPorAtivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrosPorAtivo", Namespace="http://tempuri.org/", Order=0)]
        public M4.RegistrosService.RegistrosPorAtivoRequestBody Body;
        
        public RegistrosPorAtivoRequest() {
        }
        
        public RegistrosPorAtivoRequest(M4.RegistrosService.RegistrosPorAtivoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrosPorAtivoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identificacao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string codigo;
        
        public RegistrosPorAtivoRequestBody() {
        }
        
        public RegistrosPorAtivoRequestBody(string identificacao, string codigo) {
            this.identificacao = identificacao;
            this.codigo = codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrosPorAtivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrosPorAtivoResponse", Namespace="http://tempuri.org/", Order=0)]
        public M4.RegistrosService.RegistrosPorAtivoResponseBody Body;
        
        public RegistrosPorAtivoResponse() {
        }
        
        public RegistrosPorAtivoResponse(M4.RegistrosService.RegistrosPorAtivoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrosPorAtivoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement RegistrosPorAtivoResult;
        
        public RegistrosPorAtivoResponseBody() {
        }
        
        public RegistrosPorAtivoResponseBody(System.Xml.Linq.XElement RegistrosPorAtivoResult) {
            this.RegistrosPorAtivoResult = RegistrosPorAtivoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegistrosSoapChannel : M4.RegistrosService.RegistrosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrosSoapClient : System.ServiceModel.ClientBase<M4.RegistrosService.RegistrosSoap>, M4.RegistrosService.RegistrosSoap {
        
        public RegistrosSoapClient() {
        }
        
        public RegistrosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        M4.RegistrosService.AtualizarRegistrosResponse M4.RegistrosService.RegistrosSoap.AtualizarRegistros(M4.RegistrosService.AtualizarRegistrosRequest request) {
            return base.Channel.AtualizarRegistros(request);
        }
        
        public System.Xml.Linq.XElement AtualizarRegistros(string identificacao, string crc, string codigo, string primeiroRegistro, string ultimoRegistro) {
            M4.RegistrosService.AtualizarRegistrosRequest inValue = new M4.RegistrosService.AtualizarRegistrosRequest();
            inValue.Body = new M4.RegistrosService.AtualizarRegistrosRequestBody();
            inValue.Body.identificacao = identificacao;
            inValue.Body.crc = crc;
            inValue.Body.codigo = codigo;
            inValue.Body.primeiroRegistro = primeiroRegistro;
            inValue.Body.ultimoRegistro = ultimoRegistro;
            M4.RegistrosService.AtualizarRegistrosResponse retVal = ((M4.RegistrosService.RegistrosSoap)(this)).AtualizarRegistros(inValue);
            return retVal.Body.AtualizarRegistrosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        M4.RegistrosService.RegistrosPorAtivoResponse M4.RegistrosService.RegistrosSoap.RegistrosPorAtivo(M4.RegistrosService.RegistrosPorAtivoRequest request) {
            return base.Channel.RegistrosPorAtivo(request);
        }
        
        public System.Xml.Linq.XElement RegistrosPorAtivo(string identificacao, string codigo) {
            M4.RegistrosService.RegistrosPorAtivoRequest inValue = new M4.RegistrosService.RegistrosPorAtivoRequest();
            inValue.Body = new M4.RegistrosService.RegistrosPorAtivoRequestBody();
            inValue.Body.identificacao = identificacao;
            inValue.Body.codigo = codigo;
            M4.RegistrosService.RegistrosPorAtivoResponse retVal = ((M4.RegistrosService.RegistrosSoap)(this)).RegistrosPorAtivo(inValue);
            return retVal.Body.RegistrosPorAtivoResult;
        }
    }
}
