//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M4.AtualizacaoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AtualizacaoService.AtualizacaoSoap")]
    public interface AtualizacaoSoap {
        
        // CODEGEN: Generating message contract since element name identificacao from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetalhesAtualizacao", ReplyAction="*")]
        M4.AtualizacaoService.DetalhesAtualizacaoResponse DetalhesAtualizacao(M4.AtualizacaoService.DetalhesAtualizacaoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DetalhesAtualizacaoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DetalhesAtualizacao", Namespace="http://tempuri.org/", Order=0)]
        public M4.AtualizacaoService.DetalhesAtualizacaoRequestBody Body;
        
        public DetalhesAtualizacaoRequest() {
        }
        
        public DetalhesAtualizacaoRequest(M4.AtualizacaoService.DetalhesAtualizacaoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DetalhesAtualizacaoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identificacao;
        
        public DetalhesAtualizacaoRequestBody() {
        }
        
        public DetalhesAtualizacaoRequestBody(string identificacao) {
            this.identificacao = identificacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DetalhesAtualizacaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DetalhesAtualizacaoResponse", Namespace="http://tempuri.org/", Order=0)]
        public M4.AtualizacaoService.DetalhesAtualizacaoResponseBody Body;
        
        public DetalhesAtualizacaoResponse() {
        }
        
        public DetalhesAtualizacaoResponse(M4.AtualizacaoService.DetalhesAtualizacaoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DetalhesAtualizacaoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement DetalhesAtualizacaoResult;
        
        public DetalhesAtualizacaoResponseBody() {
        }
        
        public DetalhesAtualizacaoResponseBody(System.Xml.Linq.XElement DetalhesAtualizacaoResult) {
            this.DetalhesAtualizacaoResult = DetalhesAtualizacaoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AtualizacaoSoapChannel : M4.AtualizacaoService.AtualizacaoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AtualizacaoSoapClient : System.ServiceModel.ClientBase<M4.AtualizacaoService.AtualizacaoSoap>, M4.AtualizacaoService.AtualizacaoSoap {
        
        public AtualizacaoSoapClient() {
        }
        
        public AtualizacaoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AtualizacaoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AtualizacaoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AtualizacaoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        M4.AtualizacaoService.DetalhesAtualizacaoResponse M4.AtualizacaoService.AtualizacaoSoap.DetalhesAtualizacao(M4.AtualizacaoService.DetalhesAtualizacaoRequest request) {
            return base.Channel.DetalhesAtualizacao(request);
        }
        
        public System.Xml.Linq.XElement DetalhesAtualizacao(string identificacao) {
            M4.AtualizacaoService.DetalhesAtualizacaoRequest inValue = new M4.AtualizacaoService.DetalhesAtualizacaoRequest();
            inValue.Body = new M4.AtualizacaoService.DetalhesAtualizacaoRequestBody();
            inValue.Body.identificacao = identificacao;
            M4.AtualizacaoService.DetalhesAtualizacaoResponse retVal = ((M4.AtualizacaoService.AtualizacaoSoap)(this)).DetalhesAtualizacao(inValue);
            return retVal.Body.DetalhesAtualizacaoResult;
        }
    }
}
